package com.yc.crm.jyn.dto;

import java.io.Serializable;

public class UserDto implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_user_tab.id
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_user_tab.mobile
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_user_tab.password
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yc_user_tab.type
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yc_user_tab
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_user_tab.id
     *
     * @return the value of yc_user_tab.id
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_user_tab.id
     *
     * @param id the value for yc_user_tab.id
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_user_tab.mobile
     *
     * @return the value of yc_user_tab.mobile
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_user_tab.mobile
     *
     * @param mobile the value for yc_user_tab.mobile
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_user_tab.password
     *
     * @return the value of yc_user_tab.password
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_user_tab.password
     *
     * @param password the value for yc_user_tab.password
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yc_user_tab.type
     *
     * @return the value of yc_user_tab.type
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yc_user_tab.type
     *
     * @param type the value for yc_user_tab.type
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }
}