package com.yc.crm.jyn.dao;

import java.util.List;

import com.yc.crm.jyn.dto.UserDto;

public interface UserDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user_tab
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user_tab
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    int insert(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user_tab
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    int insertSelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user_tab
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    UserDto selectByPrimaryKey(Long id);
    
    List<UserDto> getAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user_tab
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    int updateByPrimaryKeySelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yc_user_tab
     *
     * @mbg.generated Thu Dec 29 11:11:23 CST 2016
     */
    int updateByPrimaryKey(UserDto record);
}